# This is a very simple Knative Service that writes the input request to its log.
# Subscription from the GcpPubSubSource's output Channel to the Knative Service below.

apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: cron-subscription
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: cron-channel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: my-service
