apiVersion: sources.eventing.knative.dev/v1alpha1
kind: CronJobSource
metadata:
  name: cron-source
  namespace: default
spec:
  schedule: "*/2 * * * *"
  data: '{"message": "Hello world2!"}'
  sink:
    apiVersion: serving.knative.dev/v1alpha1
    kind: Broker
    name: default
