# Replace the following before applying this file:
#   MY_GCP_PROJECT: Replace with the GCP Project's ID.

apiVersion: sources.eventing.knative.dev/v1alpha1
kind: GcpPubSubSource
metadata:
  name: gcp-raw-event-source
spec:
  gcpCredsSecret:  # A secret in the knative-sources namespace
    name: google-cloud-key
    key: key.json
  googleCloudProject: arv-project-233314  # Replace this
  topic: raw_event
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: isv-channel
