# Replace the following before applying this file:
#   MY_GCP_PROJECT: Replace with the GCP Project's ID.

apiVersion: sources.eventing.knative.dev/v1alpha1
kind: GcpPubSubSource
metadata:
  name: gcp-raw-event-source-updated
spec:
  gcpCredsSecret:  # A secret in the knative-sources namespace
    name: raw-event-google-cloud-key
    key: key.json
  googleCloudProject: knative-broker  # Replace this
  topic: raw_event # Replace this if needed
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: isv-channel
